on: push

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Compress images
        run: |
          pip install pillow
          ./scripts/compress.sh

      - name: Build image
        run: docker build . -t ghcr.io/club-rockets/clubrockets.ca:latest

      - name: Push
        run: docker push --all-tags ghcr.io/club-rockets/clubrockets.ca