on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Build
        run: |
          npm install
          npm run build
          cp -r public/ dist/

      - uses: actions/upload-artifact@v3
        with:
          name: clubrockets.ca
          path: dist/